import 'package:flutter/material.dart';

import '../enum/font_options.dart';

class AppTextThemes {
  // --------------------------------------
  // Light Text Theme
  // --------------------------------------
  static TextTheme lightTextTheme(FontOptions fontFamilyOption) =>
      const TextTheme(
        displayLarge: TextStyle(
          color: Colors.black,
          fontWeight: FontWeight.w400,
          fontSize: 56,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        displayMedium: TextStyle(
          color: Colors.black,
          fontWeight: FontWeight.w400,
          fontSize: 25,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        displaySmall: TextStyle(
          color: Colors.black,
          fontWeight: FontWeight.w400,
          fontSize: 23,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        headlineLarge: TextStyle(
          color: Colors.black,
          fontWeight: FontWeight.w600,
          fontSize: 21,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        headlineMedium: TextStyle(
          color: Colors.black,
          fontWeight: FontWeight.w600,
          fontSize: 19,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        headlineSmall: TextStyle(
          color: Colors.black,
          fontWeight: FontWeight.w700,
          fontSize: 17,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        titleLarge: TextStyle(
          color: Colors.black,
          fontWeight: FontWeight.w500,
          fontSize: 17,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        titleMedium: TextStyle(
          color: Colors.black,
          fontWeight: FontWeight.w700,
          fontSize: 17,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        titleSmall: TextStyle(
          color: Colors.black,
          fontWeight: FontWeight.w500,
          fontSize: 17,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        bodyLarge: TextStyle(
          color: Colors.black,
          fontWeight: FontWeight.w400,
          fontSize: 17,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        bodyMedium: TextStyle(
          color: Colors.black,
          fontWeight: FontWeight.w400,
          fontSize: 15,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        bodySmall: TextStyle(
          color: Colors.black,
          fontWeight: FontWeight.w400,
          fontSize: 13,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        labelLarge: TextStyle(
          color: Colors.black,
          fontWeight: FontWeight.w500,
          fontSize: 13,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        labelMedium: TextStyle(
          color: Colors.black,
          fontWeight: FontWeight.w500,
          fontSize: 11,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        labelSmall: TextStyle(
          color: Colors.black,
          fontWeight: FontWeight.w500,
          fontSize: 9,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
      );

  // --------------------------------------
  // Dark Text Theme
  // --------------------------------------
  static TextTheme darkTextTheme(FontOptions fontFamilyOption) =>
      const TextTheme(
        displayLarge: TextStyle(
          color: Colors.white,
          fontWeight: FontWeight.w400,
          fontSize: 28,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        displayMedium: TextStyle(
          color: Colors.white,
          fontWeight: FontWeight.w400,
          fontSize: 24,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        displaySmall: TextStyle(
          color: Colors.white,
          fontWeight: FontWeight.w400,
          fontSize: 22,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        headlineLarge: TextStyle(
          color: Colors.white,
          fontWeight: FontWeight.w600,
          fontSize: 20,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        headlineMedium: TextStyle(
          color: Colors.white,
          fontWeight: FontWeight.w600,
          fontSize: 18,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        headlineSmall: TextStyle(
          color: Colors.white,
          fontWeight: FontWeight.w700,
          fontSize: 16,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        titleLarge: TextStyle(
          color: Colors.white,
          fontWeight: FontWeight.w500,
          fontSize: 16,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        titleMedium: TextStyle(
          color: Colors.white,
          fontWeight: FontWeight.w700,
          fontSize: 14,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        titleSmall: TextStyle(
          color: Colors.white,
          fontWeight: FontWeight.w500,
          fontSize: 14,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        bodyLarge: TextStyle(
          color: Colors.white,
          fontWeight: FontWeight.w400,
          fontSize: 16,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        bodyMedium: TextStyle(
          color: Colors.white,
          fontWeight: FontWeight.w400,
          fontSize: 14,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        bodySmall: TextStyle(
          color: Colors.white,
          fontWeight: FontWeight.w400,
          fontSize: 12,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        labelLarge: TextStyle(
          color: Colors.white,
          fontWeight: FontWeight.w500,
          fontSize: 12,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        labelMedium: TextStyle(
          color: Colors.white,
          fontWeight: FontWeight.w500,
          fontSize: 10,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
        labelSmall: TextStyle(
          color: Colors.white,
          fontWeight: FontWeight.w500,
          fontSize: 8,
          fontFamily: "ProximaNova",
          decoration: TextDecoration.none,
          decorationThickness: 0,
        ),
      );
}
